---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
         - name: auth-container
           image: manisha03b/pythonapp:authimage
           ports:
             - containerPort: 5001
           envFrom:
              - configMapRef:
                  name: app-config
            
           resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "128Mi"

           
