---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-resource-quota
spec:
  hard:
    pods: "20"
    requests.cpu: "3"
    requests.memory: "3Gi"
    limits.cpu: "5"
    limits.memory: "5Gi"
